# Copyright (c) NetworkFusion 2023
# See LICENSE file in the project root for full license information.

# This workflow will build the libdragon N64 GCC toolchain to keep it up-to-date.
name: Build latest libdragon N64 MIPS GCC toolchain

on:
  # This action will take about 40-70 minutes to run!
  # TODO: Should actually do it on cron once a month (if not manually run).
  push:
  pull_request:
  
jobs:
  build-toolchain:
    # targets the oldest ubuntu image available to create valid packages for as many versions possible.
    # TODO: move to using a docker container to support older versions.
    runs-on: ubuntu-20.04
    outputs:
      gcc-version: ${{ steps.gcc-version-generator.outputs.GCC_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        include: [
          { target-platform: Windows-x86_64, host: x86_64-w64-mingw32 },
#          { target-platform: Windows-i686, host: i686-w64-mingw32 },
          { target-platform: Linux-x86_64, host: '' }
        ]

    steps:
      - name: Install native system build dependencies
        run: |
          sudo apt-get install libmpfr-dev
          sudo apt-get install texinfo
          sudo apt-get install libmpc-dev
          sudo apt-get install squashfs-tools
          # If there are other dependencies, we should add them here and make sure the documentation is updated!

      - name: Install x-compile system build dependencies
        if: ${{ matrix.target-platform == 'Windows-x86_64' }}
        run: |
          sudo apt-get install -y mingw-w64
          # If there are other dependencies, we should add them here and make sure the documentation is updated!

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby
      - name: Set up Ruby
        if: ${{ matrix.target-platform == 'Linux-x86_64' }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.1'

      - name: Install Package Creator
        if: ${{ matrix.target-platform == 'Linux-x86_64' }}
        run: |
          echo installing jordansissel/fpm ruby package
          gem install fpm
          fpm --version
        continue-on-error: true

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: dragonminded/libdragon
          fetch-depth: 1 # we only require the last check-in, unless we want to create a changelog.

      # Cache and restore dependencies instead of downloading them to increase build speed.
      # Expires after 7 days.
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ./tools/**/*.tar.gz
            ./tools/**/*.tar.bz2
          key: ${{ runner.os }}-dependency-downloads # TODO: concurrency errors may currently occur due to matrix, but they are the same files.

      - name: Get versions from toolchain file
        id: gcc-version-generator
        run: |
          echo "BINUTILS_VERSION=$(grep -Po 'BINUTILS_V=\K[^"]*' ./tools/build-toolchain.sh)" >> $GITHUB_OUTPUT
          echo "GCC_VERSION=$(grep -Po 'GCC_V=\K[^"]*' ./tools/build-toolchain.sh)" >> $GITHUB_OUTPUT
          echo "NEWLIB_VERSION=$(grep -Po 'NEWLIB_V=\K[^"]*' ./tools/build-toolchain.sh)" >> $GITHUB_OUTPUT
        continue-on-error: false

      - name: Build N64 MIPS GCC toolchain for ${{ matrix.target-platform }}
        run: |
          # required for newlib (as not the default?!)
          export PATH="$PATH:${{ runner.temp }}/n64-brew"
          cd ./tools/
          sudo N64_INST=${{ runner.temp }}/n64-brew HOST=${{ matrix.host }} ./build-toolchain.sh
        continue-on-error: true

      # https://fpm.readthedocs.io/en/v1.15.0/getting-started.html
      - name: Generate toolchain packages for UNIX based OS
        if: ${{ matrix.target-platform == 'Linux-x86_64' }}
        run: |
          echo Generating debian package
          fpm \
            -t deb \
            -s dir \
            -p $Package_Name-$Package_Version-$Package_Revision-any.deb \
            --name $Package_Name \
            --license $Package_License \
            --version $Package_Version \
            --architecture all \
            --depends bash \
            --description "$Package_Description" \
            --url "$Package_Url" \
            --maintainer "$Package_Maintainer" \
            ${{ runner.temp }}/n64-brew/=/usr/local/

          echo Generating rpm package
          fpm \
            -t rpm \
            -s dir \
            -p $Package_Name-$Package_Version-$Package_Revision-x86_64.rpm \
            --name $Package_Name \
            --license $Package_License \
            --version $Package_Version \
            --architecture x86_64 \
            --depends nginx \
            --description "$Package_Description" \
            --url "$Package_Url" \
            --maintainer "$Package_Maintainer" \
            ${{ runner.temp }}/n64-brew/=/usr/local/
        continue-on-error: true
        env:
          Package_Name: gcc-toolchain-mips64-linux64
          Package_Version: ${{ steps.gcc-version-generator.outputs.GCC_VERSION }}
          Package_Revision: ${{ github.run_id }}
          Package_License: GPL
          Package_Description: MIPS GCC toolchain for the N64
          Package_Url: https://n64brew.com
          Package_Maintainer: N64 Brew Community

      - name: Compress Windows-x86_64 Build Artifacts
        if: ${{ matrix.target-platform == 'Windows-x86_64' }}
        run: |
          cd ${{ runner.temp }}/n64-brew/
          zip -r -q ${{ runner.temp }}/gcc-toolchain-mips64-Windows-x86_64.zip *
        continue-on-error: true

      - name: Publish Windows-x86_64 Build Artifact
        if: ${{ matrix.target-platform == 'Windows-x86_64' }}
        uses: actions/upload-artifact@v3
        with:
          name: gcc-toolchain-mips64-${{ matrix.target-platform }}
          path: |
            ${{ runner.temp }}/**/*.zip
        continue-on-error: true

      - name: Publish Linux-x86_64 Build Artifacts
        if: ${{ matrix.target-platform == 'Linux-x86_64' }}
        uses: actions/upload-artifact@v3
        with:
          name: gcc-toolchain-mips64-${{ matrix.target-platform }}
          path: |
            ./**/*.deb
            ./**/*.rpm
        continue-on-error: true

  release:
    runs-on: ubuntu-latest
#    if: github.event_name == 'release' && github.event.action == 'created'
    needs: build-toolchain

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gcc-toolchain-mips64-Windows-x86_64
          path: ${{ runner.temp }}/gcc-toolchain-mips64-Windows-x86_64

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gcc-toolchain-mips64-Linux-x86_64
          path: ${{ runner.temp }}/gcc-toolchain-mips64-Linux-x86_64

      - name: Display structure of downloaded files
        run: |
          cd ${{ runner.temp }}
          ls -R

      - name: Generate Draft Pre-Release
#        if: startsWith(github.ref, 'refs/heads/master') # Actually, should we only do it on a tag?! if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: "V${{ needs.build-toolchain.outputs.gcc-version }}-${{ github.run_id }}"
          # tag_name: "latest"
          files: |
            ${{ runner.temp }}/**/*.deb
            ${{ runner.temp }}/**/*.rpm
            ${{ runner.temp }}/**/*.zip
            # LICENSE
